CREATE DATABASE IF NOT EXISTS CONTROL_PACIENTES;

USE CONTROL_PACIENTES;

CREATE TABLE IF NOT EXISTS PACIENTES (
  ID_PACIENTE INT NOT NULL,
  NOM_PACIENTE CHAR(30) NOT NULL,
  APP_PACIENTE CHAR(30) NOT NULL,
  APM_PACIENTE CHAR(30) NOT NULL,
  GENERO TINYINT NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  ALTURA SMALLINT NOT NULL,
  PESO FLOAT NOT NULL,
  TIPO_SANGRE CHAR(4) NOT NULL,
  NUM_TELEFONO CHAR(15) NOT NULL,
  EMAIL CHAR(60) NOT NULL,
  CONSTRAINT PK_PACIENTES PRIMARY KEY (ID_PACIENTE)
);

CREATE TABLE IF NOT EXISTS DOCTOR (
  CED_DOCTOR INT NOT NULL,
  NOM_DOCTOR CHAR(30) NOT NULL,
  CONSTRAINT PK_DOCTOR PRIMARY KEY (CED_DOCTOR)
);

CREATE TABLE IF NOT EXISTS ESPECIALIDAD (
  CLAVE_ESP INT NOT NULL,
  NOM_ESP CHAR(30) NOT NULL,
  CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (CLAVE_ESP)
);

CREATE TABLE IF NOT EXISTS MEDICAMENTOS (
  CODIGO_MED INT NOT NULL,
  NOM_MED CHAR(30) NOT NULL,
  CADUCIDAD_MED DATE NOT NULL,
  CANTIDAD_MED SMALLINT NOT NULL,
  CONSTRAINT PK_MEDICAMENTOS PRIMARY KEY (CODIGO_MED)
);

CREATE TABLE IF NOT EXISTS RECETAS (
  NUM_RECETA INT NOT NULL,
  ID_PACIENTE INT NOT NULL,
  DOSIS VARCHAR(100) NOT NULL,
  CONSTRAINT PK_RECETAS PRIMARY KEY (NUM_RECETA),
  CONSTRAINT FK_RECETAS_PACIENTES FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE) 
);

CREATE TABLE IF NOT EXISTS MEDICOS_ESPECIALISTAS (
  CED_DOCTOR INT NOT NULL,
  CLAVE_ESP INT NOT NULL,
  CONSTRAINT PK_MEDICOS_ESPECIALISTAS PRIMARY KEY (CED_DOCTOR, CLAVE_ESP),
  CONSTRAINT FK_MEDICOS_ESPECIALISTAS_DOCTOR FOREIGN KEY (CED_DOCTOR) REFERENCES DOCTOR(CED_DOCTOR),
  CONSTRAINT FK_MEDICOS_ESPECIALISTAS_ESPECIALIDAD FOREIGN KEY (CLAVE_ESP) REFERENCES ESPECIALIDAD(CLAVE_ESP)
);

CREATE TABLE IF NOT EXISTS LISTA_MEDICAMENTOS (
  NUM_RECETA INT NOT NULL,
  CODIGO_MED INT NOT NULL,
  CONSTRAINT PK_LISTA_MEDICAMENTOS PRIMARY KEY (NUM_RECETA, CODIGO_MED),
  CONSTRAINT FK_LISTA_MEDICAMENTOS_RECETAS FOREIGN KEY (NUM_RECETA) REFERENCES RECETAS(NUM_RECETA),
  CONSTRAINT FK_LISTA_MEDICAMENTOS_MEDICAMENTOS FOREIGN KEY (CODIGO_MED) REFERENCES MEDICAMENTOS(CODIGO_MED)
);

CREATE TABLE IF NOT EXISTS CONSULTA_MEDICA (
  ID_CONSULTA INT NOT NULL,
  FECHA_CONSULTA DATE NOT NULL,
  HORA_CONSULTA TIME NOT NULL,
  ID_PACIENTE INT NOT NULL,
  NUM_RECETA INT NOT NULL,
  CED_DOCTOR INT NOT NULL,
  CLAVE_ESP INT NOT NULL,
  CONSTRAINT PK_CONSULTA_MEDICA PRIMARY KEY (ID_CONSULTA),
  CONSTRAINT FK_CONSULTA_MEDICA_PACIENTES FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
  CONSTRAINT FK_CONSULTA_MEDICA_RECETAS FOREIGN KEY (NUM_RECETA) REFERENCES RECETAS(NUM_RECETA),
  CONSTRAINT FK_CONSULTA_MEDICA_DOCTOR FOREIGN KEY (CED_DOCTOR) REFERENCES DOCTOR(CED_DOCTOR),
  CONSTRAINT FK_CONSULTA_MEDICA_ESPECIALIDAD FOREIGN KEY (CLAVE_ESP) REFERENCES ESPECIALIDAD(CLAVE_ESP)
);
